[project]
name = "ascii-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pillow>=12.1.1",
    "tqdm>=4.67.3",
]
